baseURL = 'https://navegadordonexus.netlify.app/'
languageCode = 'pt-pt'
title = 'Navegador do Nexus'
theme = 'ananke'

[params]
  author = 'Rjaac78'
  email = 'Rjaac78@gmail.com'

  [[params.ananke.social.follow]]
    networks = [
      'instagram',
      'facebook',
      'x-twitter'
    ]

  [params.ananke.social.networks.instagram]
    url = 'https://www.instagram.com/rjaac78social/'
  
  [params.ananke.social.networks.facebook]
    url = 'https://www.facebook.com/rjaac78social/'

  [params.ananke.social.networks.x-twitter]
    url = 'https://x.com/Rjaac78_Social'
